login page
ailab-dev/app_buy_sell pull request #15
Opened 2024-01-19 05:51 UTC by PhongTaKiai

2024-01-24 01:59 UTC, mafreud commented
@PhongTaKiai  cc: @rick1919  Thank you for creating a PR. Unfortunately, this code doesn't have a firebase. Please re-send PR to us after adding Firebase.

2024-01-24 06:55 UTC, PhongTaKiai commented
@mafreud I updated firebase

2024-01-24 07:13 UTC, mafreud commented
@PhongTaKiai Thank you.
@rick1919 UI確認していただけますか？

2024-01-25 13:53 UTC, rick1919 commented
@mafreud 
漏れすみません！
LGTMです！

@PhongTaKiai 
I'm okay with it.

2024-01-27 01:38 UTC, mafreud requested changes

2024-01-27 01:38 UTC, mafreud commented on analysis_options.yaml
> +# This file configures the analyzer, which statically analyzes Dart code to
Could you remove all unused comment out?

2024-01-27 01:38 UTC, mafreud commented on test/widget_test.dart
> +// This is a basic Flutter widget test.
Please remove unused codes.

2024-01-27 01:38 UTC, mafreud commented on pubspec.yaml
> +  cupertino_icons: ^1.0.2
Please use riverpod and riverpod generator for state management.
We won't use rxdart, koin, koin_flutter, and provider.
Besides, could you follow this project structure?

https://codewithandrea.com/articles/flutter-project-structure/#how-to-do-feature-first-the-right-way

2024-01-27 01:39 UTC, mafreud commented
@PhongTaKiai Sorry, I forgot to mention. Please use ```flutterfire configure``` to configure Firebase.

2024-01-30 06:55 UTC, PhongTaKiai commented
@mafreud i fixed comments, pls review again, thank

2024-01-30 06:56 UTC, mafreud commented
@PhongTaKiai Thanks

2024-01-30 09:50 UTC, mafreud requested changes

2024-01-30 09:50 UTC, mafreud commented on pubspec.yaml
> +  cupertino_icons: ^1.0.2
Please sort packages alphabetically.

2024-01-30 09:50 UTC, mafreud commented on lib/src/utils/navigation.dart
> +    return await Navigator.of(context).push(MaterialPageRoute(
Please use go_router because this app may need a deep link someday. It is not easy to implement deep link with Navigator 1.0.

2024-01-30 09:50 UTC, mafreud commented on lib/src/common_widgets/gird_pull_to_refersh.dart
> +class GridPullToRefresh extends StatefulWidget {
Do you use this widget? If not, please delete it and add it when you need it.

2024-01-30 09:50 UTC, mafreud commented on lib/src/features/home/home_page.dart
> +class HomePage extends ConsumerStatefulWidget {
Please use the Stateless widget instead since it is more straightforward. If possible, use flutter_hooks instead of initState and Stateful Widget.

2024-01-31 11:25 UTC, PhongTaKiai commented
@mafreud i fixed all isssues, thank

2024-01-31 13:40 UTC, mafreud approved these changes
LGTM 🎉

2024-01-31 13:41 UTC, merged