up app
ailab-dev/app_buy_sell pull request #23
Opened 2024-02-15 08:58 UTC by PhongTaKiai

2024-02-15 16:17 UTC, rick1919 reviewed
The UI is LGTM!

2024-03-12 02:22 UTC, mafreud requested changes

2024-03-12 02:22 UTC, mafreud commented on lib/src/features/home/presentation/home_page.dart
> +          context.push('/up-app');
Upload-app is a better name.

2024-03-12 02:22 UTC, mafreud commented on lib/src/features/up_app/up_app_page.dart
> +class UpAppPage extends HookConsumerWidget {
You don't use ```WidgetRef``` or ```hooks```.  ```Stateless Widget``` is enough.

2024-03-12 03:10 UTC, PhongTaKiai commented
@mafreud fixed, thank

2024-03-12 03:13 UTC, merged