android build config
ailab-dev/app_buy_sell pull request #44
Opened 2024-03-29 07:17 UTC by PhongTaKiai

2024-03-29 07:29 UTC, mafreud commented
@PhongTaKiai Please share jks and key properties with us on Slack.

2024-03-29 07:36 UTC, rick1919 commented
@PhongTaKiai 
Thank you for the invitation.

I've finished installing the file Android/iOS, so please approve it!

2024-03-29 08:51 UTC, mafreud requested changes

2024-03-29 08:51 UTC, mafreud commented on android/app/build.gradle
>      namespace "com.example.app_buy_sell"
As far as I know, Google doesn't allow us to use "example" in bundle id. Could you change it to com.app_buy_sell.release?

2024-03-29 09:03 UTC, PhongTaKiai commented
@mafreud i updated namespace same as app ID

2024-04-01 09:06 UTC, mafreud commented
@PhongTaKiai as I mentioned, could you change it to ```com.app_buy_sell.release```?

2024-04-01 09:28 UTC, PhongTaKiai commented
> @PhongTaKiai as I mentioned, could you change it to `com.app_buy_sell.release`?

ok, i updated to com.app_buy_sell.release

2024-04-01 09:45 UTC, mafreud commented
@PhongTaKiai Thanks. Please update the Firebase config so that the app can connect to Firebase.

2024-04-01 09:49 UTC, PhongTaKiai commented
> @PhongTaKiai Thanks. Please update the Firebase config so that the app can connect to Firebase.

@mafreud Can you explain more, change namespace or appId?

2024-04-01 10:04 UTC, mafreud commented
@PhongTaKiai Since the app id has been changed, you need to update google-service.json to connect to Firebase.

2024-04-02 01:47 UTC, PhongTaKiai commented
> @PhongTaKiai Since the app id has been changed, you need to update google-service.json to connect to Firebase.

@mafreud namespace and appid are different, 
now appid is com.ailab.appBuySell, do you want change appid?

2024-04-02 01:48 UTC, mafreud commented
@PhongTaKiai If your build can connect to the Firestore in your environment, it's okay.

2024-04-02 02:00 UTC, PhongTaKiai commented
@mafreud Using firebase is no problem, I have updated the namespace, please review again

2024-04-02 02:03 UTC, mafreud commented
Please test the build and upload the video. @PhongTaKiai

2024-04-02 03:08 UTC, PhongTaKiai commented
https://github.com/ailab-dev/app_buy_sell/assets/117698659/ee8d42cf-8d69-41e9-b32c-cf1654e0faf4

@mafreud uploaded video

2024-04-02 05:57 UTC, mafreud approved these changes
LGTM 🎉

2024-04-02 05:57 UTC, merged